version: "3.7"
services:
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file: .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file: .env