CREATE TABLE IF NOT EXISTS product_tag(
id INTEGER PRIMARY KEY,
name VARCHAR(15) UNIQUE NOT NULL,
vendor_id INTEGER NOT NULL,
date_created TIMESTAMP WITH TIME ZONE NOT NULL,
date_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT product_tag_vendor_id_fk
	FOREIGN KEY(vendor_id) REFERENCES vendor(id)
	ON DELETE CASCADE
);