ALTER TABLE vendor
ADD COLUMN business_type SMALLINT DEFAULT 0,
ADD COLUMN incorporation_no INTEGER UNIQUE NOT NULL,
ADD COLUMN incorporation_type SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN logo VARCHAR(255),
ADD COLUMN address VARCHAR(200),
ADD COLUMN city VARCHAR(30),
ADD COLUMN _state VARCHAR(30),
ADD COLUMN postal_code VARCHAR(10),
ADD COLUMN country VARCHAR(50);