ALTER TABLE product
ADD COLUMN images TEXT DEFAULT ' ',
ADD COLUMN is_ready BOOL DEFAULT FALSE,
ADD COLUMN is_published BOOL DEFAULT FALSE,
ADD COLUMN rating_sum DECIMAL DEFAULT 0,
ADD COLUMN no_of_ratings INTEGER DEFAULT 0,
ADD COLUMN preparation_time_mins SMALLINT DEFAULT 0,
ADD COLUMN delivery_time_mins SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS currency CHAR(3) DEFAULT 'NGN';

