
ALTER TABLE app_user
DROP COLUMN address,
DROP COLUMN city,
DROP COLUMN _state,
DROP COLUMN postal_code,
DROP COLUMN country;

CREATE TABLE IF NOT EXISTS app_user_location(
id UUID PRIMARY KEY,
user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
address VARCHAR(200) NOT NULL,
city VARCHAR(30) NOT NULL,
_state VARCHAR(30) NOT NULL,
postal_code VARCHAR(10),
country VARCHAR(50) NOT NULL,
date_created TIMESTAMP WITH TIME ZONE NOT NULL,
date_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE customer_order ADD COLUMN location_id UUID NOT NULL
REFERENCES app_user_location(id) ON DELETE CASCADE;