CREATE TABLE IF NOT EXISTS rider (
id UUID PRIMARY KEY,
name VARCHAR(200) NOT NULL,
phone_no VARCHAR(16) NOT NULL,
date_created TIMESTAMP WITH TIME ZONE NOT NULL,
date_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE app_user ADD COLUMN rider_id UUID REFERENCES rider(id) ON DELETE SET NULL;
ALTER TABLE customer_order ADD COLUMN rider_id UUID REFERENCES rider(id) ON DELETE SET NULL;